app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use App\Lib\Nii\Tree as NiiTree;

//Route::group(['middleware' => ['web']], function () {

    Route::get('/login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@getLogin']);
    Route::post('/login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@postLogin']);
    Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\AuthController@logout']);

    Route::group(['namespace' => 'File'], function()
    {
        Route::post('files/wisiwyg_upload}',
            ['as' => 'files.wisiwyg_upload', 'uses' => 'FilesController@wisiwyg_upload']
        );

        Route::get('images/{id}/resized/{size}/{crop?}',
            ['as' => 'images.resized', 'uses' => 'ImagesController@resize']
        );

        Route::resource('images', 'ImagesController', ['except' => ['destroy']]);
        Route::resource('files', 'FilesController', ['except' => ['destroy']]);
    });


    Route::get('admin', function () {
        return redirect('/admin/nii');
    });


    Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'auth'], function()
    {

        Route::get('nii/{locale?}/{chain?}',
            ['as' => 'admin.nii.index', 'uses' => 'NiiController@index']
        )->where([
            'locale' => 'ru|en|kz',
            'chain'  => NiiTree::path_collection()->implode('|')
        ]);


        Route::get('sections/create/{locale}/{category_id}/{chain}',
            ['as' => 'admin.sections.create', 'uses' => 'SectionsController@create']
        )->where([
            'locale' => 'ru|en|kz',
            'chain'  => NiiTree::path_collection()->implode('|')
        ]);

        Route::get('goods/create/{category_id?}', ['as' => 'admin.goods.create', 'uses' => 'GoodsController@create']);
        Route::resource('goods', 'GoodsController', ['except' => ['create']]);

        Route::get('contents/create/{category_id?}', ['as' => 'admin.contents.create', 'uses' => 'ContentsController@create']);
        Route::resource('contents', 'ContentsController', ['except' => ['create']]);

        Route::post('sections/orderize', ['as' => 'admin.sections.orderize', 'uses' => 'SectionsController@orderize']);
        Route::resource('sections', 'SectionsController', ['except' => ['create']]);

        Route::get('singe_pages/{category_id}', [
            'as' => 'admin.single_pages',
            'uses' => 'SinglePagesController@edit'
        ])->where([
            'category_id'  => 'welcome|contacts'
        ]);

        Route::resource('single_pages', 'SinglePagesController', ['only' => ['store', 'update']]);

        Route::resource('users', 'UsersController', ['except' => ['show', 'destroy']]);

    });


    Route::group(['prefix' => '{locale?}','middleware' => ['locale']], function () {


        Route::get('/', 'WelcomeController@index');


        Route::get('{chain}',
            ['as' => 'nii.index', 'uses' => 'NiiController@index']
        )->where([
            'locale' => 'ru|en|kz',
            'chain' => NiiTree::path_collection()->implode('|')
        ]);


        Route::group(['prefix' => 'products-n-services','middleware' => ['locale']], function () {
            Route::get('{category_id}',
                ['as' => 'goods.index', 'uses' => 'GoodsController@index']
            )->where([
                'category_id' => 'products|services'
            ]);
        });




        Route::get('{single_pages_category}',
            ['as' => 'single_pages.show', 'uses' => 'SinglePagesController@show']
        )->where([
            'single_pages_category' => 'welcome|contacts'
        ]);


        Route::get('{content_category}',
            ['as' => 'contents.index', 'uses' => 'ContentsController@index']
        )->where([
            'content_category' => 'news|news'
        ]);

        Route::get('{content_category}/{id}',
            ['as' => 'contents.show', 'uses' => 'ContentsController@show']
        )->where([
            'content_category' => 'news'
        ]);


    });


//});

app/Models/Good.php
<?php

namespace App\Models;

use App\Lib\XFields\Field\BaseField;
use App\Lib\Models\Traits\LifeCycle;
use App\Lib\Models\Traits\SeoableMixin;
use App\Lib\Models\Traits\L12n\Indivisible as L12n;
use App\Lib\Models\Traits\HasXFCategoryMixin;
use App\Lib\XFields\Category\GoodCategory as Category;

use App\Lib\Models\BaseXFModel;


class Good extends BaseXFModel
{

    use LifeCycle {
        LifeCycle::__construct as private __LifeCycleConstruct;
    }

    use SeoableMixin {
        SeoableMixin::__construct as private __SeoableConstruct;
    }

    use L12n {
        L12n::__construct as private __L12nConstruct;
    }

    use HasXFCategoryMixin;

    const SLUG_FROM_FIELD = 'name';

    const CATEGORY_CLASS  = Category::class;

    protected static $fields_to_locale = ['name', 'extra_text', 'desc', 'seo_title', 'seo_keywords', 'seo_description'];

    protected $table = 'goods';

    protected $guarded = [];

    protected $casts = [
        'image_id'    => 'integer',
        'image_ids'   => 'array',
        'props'       => 'array',
        'seted_ids'   => 'array',
    ];


    protected $attributes = [
        'is_visible' => true
    ];


    protected $rules = array(
//        'name' => 'required',
        'category_id' => 'required|in:products,services',
    );



    public function scopeVisible($query) {
        return $query->where('is_visible', true);
    }



    public function __construct($attributes = [])
    {
        $this->__LifeCycleConstruct();
        $this->__L12nConstruct();
        $this->__SeoableConstruct();
        parent::__construct($attributes);
    }


    public function xfields() {
        $xfields = $this->category->fields();

        return $xfields + [
            'image_id' => BaseField::create([
                'title'   => 'Изображение',
                'storage' => 'image_id',
                'type'    => 'Image'
            ]),
//            'slider_ids' => BaseField::create([
//                'title'   => 'Слайдер',
//                'storage' => 'image_ids',
//                'type'    => 'Album',
//                'is_json' => true,
//            ]),
        ];
    }


    public function getPriceAttribute()
    {
        if ($this->category_id == 'mattress') {
            list($w, $h) = explode('x', Category::$mattress_sizes['default']);
            return $this->price_per_square_meter * $w * $h * 0.0001;
        }

        return array_get($this->attributes, 'price', null);
    }


    public function getSetedItemsAttribute() // seted_items
    {
        return static::byState('live')->whereIn('id', $this->seted_ids)->get();
    }


    public function in_my_set($id)
    {
        if (is_array($this->seted_ids)) {
            return in_array($id, $this->seted_ids);
        }
        return false;
    }



    public function slugable() {
        return $this->name; // поле из которого строиться слаг
    }


}

app/Http/Controllers/Admin/GoodsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\Good;
use App\Lib\XFields\Category\GoodCategory;

use App\Http\Controllers\Admin\Traits\SpecialActions;

class GoodsController extends Controller
{
    use SpecialActions;

    const VIEWS_FOLDER = 'goods';
    const VIEW_VAR_NAME = 'good';

    public function index(Request $request)
    {
        $state       = $request->get('state', 'live');
        $category_id = $request->session()->get('good.category_id');


        $goods      = Good::byState($state);
        if ($category_id) {
            $goods      = $goods->byCategoryId($category_id);
        }

        return view('admin.goods.index', [
            'goods'       => $goods->orderBy('created_at')->get(),
            'categories'  => GoodCategory::all(),
            'category_id' => $category_id,
            'state'       => $state
        ]);
    }

    public function create(Request $request, $category_id)
    {
        $good = new Good(['category_id' => $category_id]);
        return view('admin.goods.form', ['good' => $good]);
    }


    public function store(Request $request)
    {
        $good = new Good($this->good_params());

        return $this->run_action( $good );

    }

    public function edit(Request $request, $id)
    {
        $good = Good::find($id);
        return view('admin.goods.form', ['good'   => $good,]);
    }


    public function update(Request $request, $id)
    {
        $good = Good::find($id)
            ->fill($this->good_params());

        return $this->run_action( $good );
    }


    private function good_params()
    {
        $params  = request()->good ?: [];
        return $params;
    }

}

app/Http/Controllers/GoodsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Models\Good;

class GoodsController extends Controller
{

    public function index(Request $request, $locale, $category_id)
    {

        $goods = Good::live()->visible()
            ->byCategoryId($category_id)
            ->orderBy('created_at')
            ->get();

        return view('goods.index', [
            'goods'       => $goods,
            'category_id' => $category_id,
        ]);
    }

}

resources/views/admin/goods/form.blade.php
@extends('layouts.admin')

@section('content')

    <h1>
        {!! AdminGoodCrumbs::items( ['good' => $good ] )->last()['title']  !!}
    </h1>

    {!! AdminGoodCrumbs::show( ['good' => $good ] ) !!}

    <div class="row">

        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#info">Инфо</a></li>
            <li class=""><a data-toggle="tab" href="#seo">SEO</a></li>
            {{--<li class=""><a data-toggle="tab" href="#seted">Сопутствующие товары</a></li>--}}
        </ul>


        {!! Form::resource($good, ['route' => 'admin.goods', 'class' => 'form-horizontal']) !!}

        {!! Form::hidden('good[category_id]', $good->category_id) !!}

        <div class="tab-content">

            @include('admin.partials.errors', ['errors' => $good->errors])

            @include("admin.goods.form._info_tab")
            @include("admin.partials.form.seoable_tab._localed", ['seoable' => $good, 'seoble_type' => 'good'])
            {{--@include("admin.goods.form._seted_tab")--}}

        </div>

        @include("admin.partials.form._button_bar", ['object' => $good, 'lifecycled' => true])


        {!! Form::close() !!}

    </div>

@stop

resources/views/admin/goods/index.blade.php
@extends('layouts.admin')

@section('content_bar')

    {!! AdminFilterCell::show([
        'category' => ['categories' => $categories],
        'lifecycle' => ['route' => 'admin.contents.index']
        ])
    !!}

@stop

@section('content')

    <div class="row">

        {{--<div class="col-md-2">--}}
        {{--</div>--}}

        <h1>Товары

            <div class="btn-group">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Добавить... <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    @foreach ( $categories as $category )
                        <li> {!! link_to_route('admin.goods.create', $category->title(), ['category_id' => $category->id], []) !!} </li>
                    @endforeach
                </ul>
            </div>

        </h1>

        @if ($goods->isEmpty())
            <p>Нет ни одного товара</p>

        @else

            <table class="table table-hover">
                <colgroup>
                    <col width="70px"/>
                </colgroup>
                <thead>
                    <tr>
                        <th></th>
                        <th>Название</th>
                        <th>Категория</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>

                    @foreach ($goods as $good)
                        <tr>
                            {!! Form::resource($good, ['route' => 'admin.goods', 'route_params' => ['redirect_to' => 'index'], 'class' => 'form-horizontal']) !!}

                            <td>
                                <div class="thumbnail">
                                    @if ($good->image_id)
                                        {!! Html::thumbed_link_to_picture($good->image_id, ['target' => 'blank'], ['size' => '50', 'crop' => true]) !!}
                                    @else
                                        <div class="thumb-empty"><span class="glyphicon glyphicon-minus"></span></div>
                                    @endif
                                </div>
                            </td>
                            <td> {!! link_to_route('admin.goods.edit', $good->name, ['good_id' => $good->id]) !!} </td>
                            <td> {!! $good->category->title() !!} </td>

                            <td>
                                <div class="pull-right">
                                    @if ($good->is_live)
                                        {!! Form::submit('В архив', ['name' => 'action[move_to_archive]', 'class' => 'btn btn-primary']) !!}
                                    @elseif ($good->is_archive)
                                        {!! Form::submit('Восстановить', ['name' => 'action[move_to_live]', 'class' => 'btn btn-primary']) !!}
                                    @endif
                                </div>

                            </td>

                            {!! Form::close() !!}
                        </tr>

                    @endforeach

                </tbody>
            </table>

        @endif

    </div>
@stop